version: '3.8'

services:

  # Service for the user-service
  user-service:
    build: # Build the image from the Dockerfile
      context: ./  # This sets the root directory as the context
      dockerfile: ./services/user-service/Dockerfile
   
    container_name: user-service
    depends_on:
      - postgres  # Ensure the app starts after the postgres service
    environment:
      POSTGRES_URI: postgres://user:password@postgres:5432/usersdb  # Connection URI
    ports:
      - "8080:8080"  # Expose app on port 8080
    volumes:
      - ./services/user-service:/usr/src/app
      - ./services/user-service/index.js:/usr/src/app/index.js  # Mount the index.js file to the container

    networks:
      - app_network
    restart: always

  student-service:
    build: # Build the image from the Dockerfile
      context: ./  # This sets the root directory as the context
      dockerfile: ./services/student-service/Dockerfile

    container_name: student-service
    depends_on:
      - postgres  # Ensure the app starts after the postgres service
    environment:
      POSTGRES_URI: postgres://user:password@postgres:5432/studentsdb  # Connection URI
    ports:
      - "7070:7070"  # Expose app on port 8080
    volumes:
      - ./services/student-service:/usr/src/app
      - ./services/student-service/index.js:/usr/src/app/index.js  # Mount the index.js file to the container

    networks:
      - app_network
    restart: always

  # Service for the database
  postgres:
    image: postgres      
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user    # Database user
      POSTGRES_PASSWORD: password  # Database password
    ports:
      - "5432:5432"
    volumes:                        # To save the data in a persistent volume
      - pgdata:/var/lib/postgresql/data
      -  ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network  # Connect to the same network as the app



volumes:
  pgdata:

networks:
  app_network:  # Define the network for communication between services
    driver: bridge

