# Usa un'immagine ufficiale di Node.js
FROM node:18

# Imposta la cartella di lavoro
WORKDIR /app

# Copia i file package.json e package-lock.json e installa le dipendenze
COPY package*.json ./
RUN npm install

# Copia tutti i file dell'app
COPY . .

# Esponi la porta 5000 per il server Node.js
EXPOSE 5001

# Comando per avviare il server
CMD ["node", "server.js"]
